# Generated by Django 5.0.7 on 2024-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmacweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_deadline',
            field=models.DateField(default='2022-12-31 23:59:59'),
        ),
    ]
