# Generated by Django 5.0.7 on 2024-08-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmacweb', '0002_members_projects_tasks_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
